name: wisp
description: "Modern File Manager"
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.20.2
  dartx: ^1.2.0
  path: ^1.9.1
  path_provider: ^2.1.5
  flutter_riverpod: 2.0.0-dev.9
  # flutter_riverpod: ^3.2.1
  animations: ^2.2.0
  window_manager: ^0.4.3

  fz_actions:
    path: ../from_zero_ui/packages/fz_actions/
  fz_api_handling:
    path: ../from_zero_ui/packages/fz_api_handling/
  fz_appbar:
    path: ../from_zero_ui/packages/fz_appbar/
  fz_opacity_gradient:
    path: ../from_zero_ui/packages/fz_opacity_gradient/
  fz_popup:
    path: ../from_zero_ui/packages/fz_popup/
  fz_scrollbar:
    path: ../from_zero_ui/packages/fz_scrollbar/
  fz_tooltip:
    path: ../from_zero_ui/packages/fz_tooltip/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  intl: ^0.20.2
  archive: ^4.0.7

flutter:
  uses-material-design: true
