// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

class NativeFileBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NativeFileBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NativeFileBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  int close(int __fd) {
    return _close(__fd);
  }

  late final _closePtr = _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int)>>(
    'close',
  );
  late final _close = _closePtr.asFunction<int Function(int)>();

  int copy_file_range(
    int __infd,
    ffi.Pointer<ffi.Long> __pinoff,
    int __outfd,
    ffi.Pointer<ffi.Long> __poutoff,
    int __length,
    int __flags,
  ) {
    return _copy_file_range(
      __infd,
      __pinoff,
      __outfd,
      __poutoff,
      __length,
      __flags,
    );
  }

  late final _copy_file_rangePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Long Function(
            ffi.Int,
            ffi.Pointer<ffi.Long>,
            ffi.Int,
            ffi.Pointer<ffi.Long>,
            ffi.Size,
            ffi.UnsignedInt,
          )
        >
      >('copy_file_range');
  late final _copy_file_range = _copy_file_rangePtr
      .asFunction<
        int Function(
          int,
          ffi.Pointer<ffi.Long>,
          int,
          ffi.Pointer<ffi.Long>,
          int,
          int,
        )
      >();

  int dup(int __fd) {
    return _dup(__fd);
  }

  late final _dupPtr = _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int)>>(
    'dup',
  );
  late final _dup = _dupPtr.asFunction<int Function(int)>();

  int dup2(int __fd, int __fd2) {
    return _dup2(__fd, __fd2);
  }

  late final _dup2Ptr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Int)>>('dup2');
  late final _dup2 = _dup2Ptr.asFunction<int Function(int, int)>();

  int dup3(int __fd, int __fd2, int __flags) {
    return _dup3(__fd, __fd2, __flags);
  }

  late final _dup3Ptr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Int, ffi.Int)>>(
        'dup3',
      );
  late final _dup3 = _dup3Ptr.asFunction<int Function(int, int, int)>();

  ffi.Pointer<ffi.Int> errno_location() {
    return _errno_location();
  }

  late final _errno_locationPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Int> Function()>>(
        '__errno_location',
      );
  late final _errno_location = _errno_locationPtr
      .asFunction<ffi.Pointer<ffi.Int> Function()>();

  int fallocate(int __fd, int __mode, int __offset, int __len) {
    return _fallocate(__fd, __mode, __offset, __len);
  }

  late final _fallocatePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Int, ffi.Int, ffi.Long, ffi.Long)
        >
      >('fallocate');
  late final _fallocate = _fallocatePtr
      .asFunction<int Function(int, int, int, int)>();

  int fcntl(int __fd, int __cmd, int va) {
    return _fcntl(__fd, __cmd, va);
  }

  late final _fcntlPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Int, ffi.Int, ffi.VarArgs<(ffi.Int32,)>)
        >
      >('fcntl');
  late final _fcntl = _fcntlPtr.asFunction<int Function(int, int, int)>();

  int fdatasync(int __fildes) {
    return _fdatasync(__fildes);
  }

  late final _fdatasyncPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int)>>('fdatasync');
  late final _fdatasync = _fdatasyncPtr.asFunction<int Function(int)>();

  int fstat(int __fd, ffi.Pointer<stat> __buf) {
    return _fstat(__fd, __buf);
  }

  late final _fstatPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Pointer<stat>)>>(
        'fstat',
      );
  late final _fstat = _fstatPtr
      .asFunction<int Function(int, ffi.Pointer<stat>)>();

  int fstatat(
    int __fd,
    ffi.Pointer<ffi.Char> __file,
    ffi.Pointer<stat> __buf,
    int __flag,
  ) {
    return _fstatat(__fd, __file, __buf, __flag);
  }

  late final _fstatatPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Int,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<stat>,
            ffi.Int,
          )
        >
      >('fstatat');
  late final _fstatat = _fstatatPtr
      .asFunction<
        int Function(int, ffi.Pointer<ffi.Char>, ffi.Pointer<stat>, int)
      >();

  int fsync(int __fd) {
    return _fsync(__fd);
  }

  late final _fsyncPtr = _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int)>>(
    'fsync',
  );
  late final _fsync = _fsyncPtr.asFunction<int Function(int)>();

  int ftruncate(int __fd, int __length) {
    return _ftruncate(__fd, __length);
  }

  late final _ftruncatePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Long)>>(
        'ftruncate',
      );
  late final _ftruncate = _ftruncatePtr.asFunction<int Function(int, int)>();

  int lseek(int __fd, int __offset, int __whence) {
    return _lseek(__fd, __offset, __whence);
  }

  late final _lseekPtr =
      _lookup<
        ffi.NativeFunction<ffi.Long Function(ffi.Int, ffi.Long, ffi.Int)>
      >('lseek');
  late final _lseek = _lseekPtr.asFunction<int Function(int, int, int)>();

  int lstat(ffi.Pointer<ffi.Char> __file, ffi.Pointer<stat> __buf) {
    return _lstat(__file, __buf);
  }

  late final _lstatPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<stat>)
        >
      >('lstat');
  late final _lstat = _lstatPtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<stat>)>();

  int mkdir(ffi.Pointer<ffi.Char> __path, int __mode) {
    return _mkdir(__path, __mode);
  }

  late final _mkdirPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.UnsignedInt)
        >
      >('mkdir');
  late final _mkdir = _mkdirPtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>, int)>();

  int mkdirat(int __fd, ffi.Pointer<ffi.Char> __path, int __mode) {
    return _mkdirat(__fd, __path, __mode);
  }

  late final _mkdiratPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Int, ffi.Pointer<ffi.Char>, ffi.UnsignedInt)
        >
      >('mkdirat');
  late final _mkdirat = _mkdiratPtr
      .asFunction<int Function(int, ffi.Pointer<ffi.Char>, int)>();

  int open(ffi.Pointer<ffi.Char> __file, int __oflag, int va) {
    return _open(__file, __oflag, va);
  }

  late final _openPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Int,
            ffi.VarArgs<(ffi.Uint32,)>,
          )
        >
      >('open');
  late final _open = _openPtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>, int, int)>();

  int openat(int __fd, ffi.Pointer<ffi.Char> __file, int __oflag, int va) {
    return _openat(__fd, __file, __oflag, va);
  }

  late final _openatPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Int,
            ffi.Pointer<ffi.Char>,
            ffi.Int,
            ffi.VarArgs<(ffi.Uint32,)>,
          )
        >
      >('openat');
  late final _openat = _openatPtr
      .asFunction<int Function(int, ffi.Pointer<ffi.Char>, int, int)>();

  int posix_fallocate(int __fd, int __offset, int __len) {
    return _posix_fallocate(__fd, __offset, __len);
  }

  late final _posix_fallocatePtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Long, ffi.Long)>
      >('posix_fallocate');
  late final _posix_fallocate = _posix_fallocatePtr
      .asFunction<int Function(int, int, int)>();

  int pread(int __fd, ffi.Pointer<ffi.Void> __buf, int __nbytes, int __offset) {
    return _pread(__fd, __buf, __nbytes, __offset);
  }

  late final _preadPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Long Function(ffi.Int, ffi.Pointer<ffi.Void>, ffi.Size, ffi.Long)
        >
      >('pread');
  late final _pread = _preadPtr
      .asFunction<int Function(int, ffi.Pointer<ffi.Void>, int, int)>();

  int pwrite(int __fd, ffi.Pointer<ffi.Void> __buf, int __n, int __offset) {
    return _pwrite(__fd, __buf, __n, __offset);
  }

  late final _pwritePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Long Function(ffi.Int, ffi.Pointer<ffi.Void>, ffi.Size, ffi.Long)
        >
      >('pwrite');
  late final _pwrite = _pwritePtr
      .asFunction<int Function(int, ffi.Pointer<ffi.Void>, int, int)>();

  int read(int __fd, ffi.Pointer<ffi.Void> __buf, int __nbytes) {
    return _read(__fd, __buf, __nbytes);
  }

  late final _readPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Long Function(ffi.Int, ffi.Pointer<ffi.Void>, ffi.Size)
        >
      >('read');
  late final _read = _readPtr
      .asFunction<int Function(int, ffi.Pointer<ffi.Void>, int)>();

  int stat$1(ffi.Pointer<ffi.Char> __file, ffi.Pointer<stat> __buf) {
    return _stat$1(__file, __buf);
  }

  late final _stat$1Ptr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<stat>)
        >
      >('stat');
  late final _stat$1 = _stat$1Ptr
      .asFunction<int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<stat>)>();

  ffi.Pointer<ffi.Char> strerror(int __errnum) {
    return _strerror(__errnum);
  }

  late final _strerrorPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Int)>>(
        'strerror',
      );
  late final _strerror = _strerrorPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(int)>();

  int truncate(ffi.Pointer<ffi.Char> __file, int __length) {
    return _truncate(__file, __length);
  }

  late final _truncatePtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Long)>
      >('truncate');
  late final _truncate = _truncatePtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>, int)>();

  int write(int __fd, ffi.Pointer<ffi.Void> __buf, int __n) {
    return _write(__fd, __buf, __n);
  }

  late final _writePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Long Function(ffi.Int, ffi.Pointer<ffi.Void>, ffi.Size)
        >
      >('write');
  late final _write = _writePtr
      .asFunction<int Function(int, ffi.Pointer<ffi.Void>, int)>();
}

const int ACCESSPERMS = 511;

const int ALLPERMS = 4095;

const int AT_EACCESS = 512;

const int AT_EMPTY_PATH = 4096;

const int AT_EXECVE_CHECK = 65536;

const int AT_FDCWD = -100;

const int AT_HANDLE_CONNECTABLE = 2;

const int AT_HANDLE_FID = 512;

const int AT_HANDLE_MNT_ID_UNIQUE = 1;

const int AT_NO_AUTOMOUNT = 2048;

const int AT_RECURSIVE = 32768;

const int AT_REMOVEDIR = 512;

const int AT_STATX_DONT_SYNC = 16384;

const int AT_STATX_FORCE_SYNC = 8192;

const int AT_STATX_SYNC_AS_STAT = 0;

const int AT_STATX_SYNC_TYPE = 24576;

const int AT_SYMLINK_FOLLOW = 1024;

const int AT_SYMLINK_NOFOLLOW = 256;

const int DEFFILEMODE = 438;

const int EACCES = 13;

const int EADDRINUSE = 98;

const int EADDRNOTAVAIL = 99;

const int EADV = 68;

const int EAFNOSUPPORT = 97;

const int EAGAIN = 11;

const int EALREADY = 114;

const int EBADE = 52;

const int EBADF = 9;

const int EBADFD = 77;

const int EBADMSG = 74;

const int EBADR = 53;

const int EBADRQC = 56;

const int EBADSLT = 57;

const int EBFONT = 59;

const int EBUSY = 16;

const int ECANCELED = 125;

const int ECHILD = 10;

const int ECHRNG = 44;

const int ECOMM = 70;

const int ECONNABORTED = 103;

const int ECONNREFUSED = 111;

const int ECONNRESET = 104;

const int EDEADLK = 35;

const int EDEADLOCK = 35;

const int EDESTADDRREQ = 89;

const int EDOM = 33;

const int EDOTDOT = 73;

const int EDQUOT = 122;

const int EEXIST = 17;

const int EFAULT = 14;

const int EFBIG = 27;

const int EHOSTDOWN = 112;

const int EHOSTUNREACH = 113;

const int EHWPOISON = 133;

const int EIDRM = 43;

const int EILSEQ = 84;

const int EINPROGRESS = 115;

const int EINTR = 4;

const int EINVAL = 22;

const int EIO = 5;

const int EISCONN = 106;

const int EISDIR = 21;

const int EISNAM = 120;

const int EKEYEXPIRED = 127;

const int EKEYREJECTED = 129;

const int EKEYREVOKED = 128;

const int EL2HLT = 51;

const int EL2NSYNC = 45;

const int EL3HLT = 46;

const int EL3RST = 47;

const int ELIBACC = 79;

const int ELIBBAD = 80;

const int ELIBEXEC = 83;

const int ELIBMAX = 82;

const int ELIBSCN = 81;

const int ELNRNG = 48;

const int ELOOP = 40;

const int EMEDIUMTYPE = 124;

const int EMFILE = 24;

const int EMLINK = 31;

const int EMSGSIZE = 90;

const int EMULTIHOP = 72;

const int ENAMETOOLONG = 36;

const int ENAVAIL = 119;

const int ENETDOWN = 100;

const int ENETRESET = 102;

const int ENETUNREACH = 101;

const int ENFILE = 23;

const int ENOANO = 55;

const int ENOBUFS = 105;

const int ENOCSI = 50;

const int ENODATA = 61;

const int ENODEV = 19;

const int ENOENT = 2;

const int ENOEXEC = 8;

const int ENOKEY = 126;

const int ENOLCK = 37;

const int ENOLINK = 67;

const int ENOMEDIUM = 123;

const int ENOMEM = 12;

const int ENOMSG = 42;

const int ENONET = 64;

const int ENOPKG = 65;

const int ENOPROTOOPT = 92;

const int ENOSPC = 28;

const int ENOSR = 63;

const int ENOSTR = 60;

const int ENOSYS = 38;

const int ENOTBLK = 15;

const int ENOTCONN = 107;

const int ENOTDIR = 20;

const int ENOTEMPTY = 39;

const int ENOTNAM = 118;

const int ENOTRECOVERABLE = 131;

const int ENOTSOCK = 88;

const int ENOTSUP = 95;

const int ENOTTY = 25;

const int ENOTUNIQ = 76;

const int ENXIO = 6;

const int EOPNOTSUPP = 95;

const int EOVERFLOW = 75;

const int EOWNERDEAD = 130;

const int EPERM = 1;

const int EPFNOSUPPORT = 96;

const int EPIPE = 32;

const int EPROTO = 71;

const int EPROTONOSUPPORT = 93;

const int EPROTOTYPE = 91;

const int ERANGE = 34;

const int EREMCHG = 78;

const int EREMOTE = 66;

const int EREMOTEIO = 121;

const int ERESTART = 85;

const int ERFKILL = 132;

const int EROFS = 30;

const int ESHUTDOWN = 108;

const int ESOCKTNOSUPPORT = 94;

const int ESPIPE = 29;

const int ESRCH = 3;

const int ESRMNT = 69;

const int ESTALE = 116;

const int ESTRPIPE = 86;

const int ETIME = 62;

const int ETIMEDOUT = 110;

const int ETOOMANYREFS = 109;

const int ETXTBSY = 26;

const int EUCLEAN = 117;

const int EUNATCH = 49;

const int EUSERS = 87;

const int EWOULDBLOCK = 11;

const int EXDEV = 18;

const int EXFULL = 54;

const int FALLOC_FL_ALLOCATE_RANGE = 0;

const int FALLOC_FL_COLLAPSE_RANGE = 8;

const int FALLOC_FL_INSERT_RANGE = 32;

const int FALLOC_FL_KEEP_SIZE = 1;

const int FALLOC_FL_NO_HIDE_STALE = 4;

const int FALLOC_FL_PUNCH_HOLE = 2;

const int FALLOC_FL_UNSHARE_RANGE = 64;

const int FALLOC_FL_WRITE_ZEROES = 128;

const int FALLOC_FL_ZERO_RANGE = 16;

const int FAPPEND = 1024;

const int FASYNC = 8192;

const int FD_CLOEXEC = 1;

const int FFSYNC = 1052672;

const int FNDELAY = 2048;

const int FNONBLOCK = 2048;

const int F_DUPFD = 0;

const int F_DUPFD_CLOEXEC = 1030;

const int F_EXLCK = 4;

const int F_GETFD = 1;

const int F_GETFL = 3;

const int F_GETOWN = 9;

const int F_GETOWN_EX = 16;

const int F_OK = 0;

const int F_RDLCK = 0;

const int F_SETFD = 2;

const int F_SETFL = 4;

const int F_SETOWN = 8;

const int F_SETOWN_EX = 15;

const int F_SHLCK = 8;

const int F_UNLCK = 2;

const int F_WRLCK = 1;

const int LOCK_EX = 2;

const int LOCK_NB = 4;

const int LOCK_SH = 1;

const int LOCK_UN = 8;

const int O_ACCMODE = 3;

const int O_APPEND = 1024;

const int O_ASYNC = 8192;

const int O_CLOEXEC = 524288;

const int O_CREAT = 64;

const int O_DIRECT = 16384;

const int O_DIRECTORY = 65536;

const int O_DSYNC = 4096;

const int O_EXCL = 128;

const int O_FSYNC = 1052672;

const int O_LARGEFILE = 0;

const int O_NDELAY = 2048;

const int O_NOATIME = 262144;

const int O_NOCTTY = 256;

const int O_NOFOLLOW = 131072;

const int O_NONBLOCK = 2048;

const int O_PATH = 2097152;

const int O_RDONLY = 0;

const int O_RDWR = 2;

const int O_RSYNC = 1052672;

const int O_SYNC = 1052672;

const int O_TMPFILE = 4259840;

const int O_TRUNC = 512;

const int O_WRONLY = 1;

const int POSIX_FADV_DONTNEED = 4;

const int POSIX_FADV_NOREUSE = 5;

const int POSIX_FADV_NORMAL = 0;

const int POSIX_FADV_RANDOM = 1;

const int POSIX_FADV_SEQUENTIAL = 2;

const int POSIX_FADV_WILLNEED = 3;

const int RWF_WRITE_LIFE_NOT_SET = 0;

const int R_OK = 4;

const int SEEK_CUR = 1;

const int SEEK_DATA = 3;

const int SEEK_END = 2;

const int SEEK_HOLE = 4;

const int SEEK_SET = 0;

const int SPLICE_F_GIFT = 8;

const int SPLICE_F_MORE = 4;

const int SPLICE_F_MOVE = 1;

const int SPLICE_F_NONBLOCK = 2;

const int S_BLKSIZE = 512;

const int S_IEXEC = 64;

const int S_IFBLK = 24576;

const int S_IFCHR = 8192;

const int S_IFDIR = 16384;

const int S_IFIFO = 4096;

const int S_IFLNK = 40960;

const int S_IFMT = 61440;

const int S_IFREG = 32768;

const int S_IFSOCK = 49152;

const int S_IREAD = 256;

const int S_IRGRP = 32;

const int S_IROTH = 4;

const int S_IRUSR = 256;

const int S_IRWXG = 56;

const int S_IRWXO = 7;

const int S_IRWXU = 448;

const int S_ISGID = 1024;

const int S_ISUID = 2048;

const int S_ISVTX = 512;

const int S_IWGRP = 16;

const int S_IWOTH = 2;

const int S_IWRITE = 128;

const int S_IWUSR = 128;

const int S_IXGRP = 8;

const int S_IXOTH = 1;

const int S_IXUSR = 64;

const int W_OK = 2;

const int X_OK = 1;

final class stat extends ffi.Struct {
  @ffi.UnsignedLong()
  external int st_dev;

  @ffi.UnsignedLong()
  external int st_ino;

  @ffi.UnsignedLong()
  external int st_nlink;

  @ffi.UnsignedInt()
  external int st_mode;

  @ffi.UnsignedInt()
  external int st_uid;

  @ffi.UnsignedInt()
  external int st_gid;

  @ffi.Int()
  external int __pad0;

  @ffi.UnsignedLong()
  external int st_rdev;

  @ffi.Long()
  external int st_size;

  @ffi.Long()
  external int st_blksize;

  @ffi.Long()
  external int st_blocks;

  external timespec st_atim;

  external timespec st_mtim;

  external timespec st_ctim;

  @ffi.Array.multi([3])
  external ffi.Array<ffi.Long> __glibc_reserved;
}

final class timespec extends ffi.Struct {
  @ffi.Long()
  external int tv_sec;

  @ffi.Long()
  external int tv_nsec;
}
